title: "Welcome to Business Analytics for Managers (MGT 6213)!"
theme: jekyll-theme-cayman
description: "By Zhaohu (Jonathan) Fan <br /> ''Analytics for Managers: Command Clarity. Deliver Impact.''" 
github:
  is_project_page: false
